spring:
  application:
    name: heroes
  data:
    mongodb:
      uri: mongodb+srv://rn_user:oZhWZ8xSbDZi64lO@cursocluster.uhjeg.mongodb.net/cursoRN?retryWrites=true&w=majority

logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE

# Server configuration
server:
  port: ${PORT_APP:8080}
  servlet:
    context-path: /api
    session:
      timeout: 30s
